export const MEMONEX_IMPRINTS_ABI = [
  // ── Read functions ────────────────────────────────────────────
  {
    type: "function",
    name: "getImprintType",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "creator", type: "address" },
          { name: "royaltyBps", type: "uint96" },
          { name: "maxSupply", type: "uint128" },
          { name: "minted", type: "uint128" },
          { name: "promoReserve", type: "uint128" },
          { name: "promoMinted", type: "uint128" },
          { name: "primaryPrice", type: "uint256" },
          { name: "contentHash", type: "bytes32" },
          { name: "active", type: "bool" },
          { name: "adminMintLocked", type: "bool" },
          { name: "collectionOnly", type: "bool" },
          { name: "metadataURI", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getListing",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "seller", type: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "amount", type: "uint128" },
          { name: "unitPrice", type: "uint128" },
          { name: "expiry", type: "uint64" },
          { name: "active", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ownsImprint",
    inputs: [
      { name: "wallet", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "remainingSupply",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verifyContentHash",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "claimedHash", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [
      { name: "account", type: "address" },
      { name: "id", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextTokenId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextCollectionId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedCollectionCreators",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCollection",
    inputs: [{ name: "collectionId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "mintPrice", type: "uint256" },
          { name: "tokenIds", type: "uint256[]" },
          { name: "rarityWeights", type: "uint256[]" },
          { name: "active", type: "bool" },
          { name: "creator", type: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCollectionAvailability",
    inputs: [{ name: "collectionId", type: "uint256" }],
    outputs: [
      { name: "availableTokenIds", type: "uint256[]" },
      { name: "effectiveWeights", type: "uint256[]" },
      { name: "totalWeight", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creatorNonces",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "IMPRINT_AUTH_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "royaltyInfo",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "salePrice", type: "uint256" },
    ],
    outputs: [
      { name: "receiver", type: "address" },
      { name: "royaltyAmount", type: "uint256" },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "uri",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },

  // ── Write functions ───────────────────────────────────────────
  {
    type: "function",
    name: "safeTransferFrom",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "id", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "data", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "purchase",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mintFromCollection",
    inputs: [{ name: "collectionId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mintFromCollection",
    inputs: [
      { name: "collectionId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createCollection",
    inputs: [
      { name: "name", type: "string" },
      { name: "mintPrice", type: "uint256" },
      { name: "tokenIds", type: "uint256[]" },
      { name: "rarityWeights", type: "uint256[]" },
    ],
    outputs: [{ name: "collectionId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "activateCollection",
    inputs: [{ name: "collectionId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivateCollection",
    inputs: [{ name: "collectionId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addImprintType",
    inputs: [
      { name: "creator", type: "address" },
      { name: "metadataURI", type: "string" },
      { name: "maxSupply", type: "uint256" },
      { name: "primaryPrice", type: "uint256" },
      { name: "royaltyBps", type: "uint96" },
      { name: "contentHash", type: "bytes32" },
      { name: "promoReserve", type: "uint256" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addImprintTypeWithSig",
    inputs: [
      { name: "creator", type: "address" },
      { name: "metadataURI", type: "string" },
      { name: "maxSupply", type: "uint256" },
      { name: "primaryPrice", type: "uint256" },
      { name: "royaltyBps", type: "uint96" },
      { name: "contentHash", type: "bytes32" },
      { name: "deadline", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "adminMint",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "data", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "listForSale",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "unitPrice", type: "uint256" },
      { name: "expiry", type: "uint64" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "buyFromHolder",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "seller", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "maxTotalPrice", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelListing",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "burn",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePrice",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "newPrice", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateContentHash",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "newContentHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateMetadataURI",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "newMetadataURI", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTreasury",
    inputs: [{ name: "newTreasury", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlatformFeeBps",
    inputs: [{ name: "newFeeBps", type: "uint96" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSecondaryFeeBps",
    inputs: [{ name: "newFeeBps", type: "uint96" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCollectionCreatorAuthorization",
    inputs: [
      { name: "account", type: "address" },
      { name: "authorized", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rescueERC1155",
    inputs: [
      { name: "tokenContract", type: "address" },
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "data", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lockAdminMint",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setImprintActive",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setApprovalForAll",
    inputs: [
      { name: "operator", type: "address" },
      { name: "approved", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isApprovedForAll",
    inputs: [
      { name: "account", type: "address" },
      { name: "operator", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },

  // ── Events ────────────────────────────────────────────────────
  {
    type: "event",
    name: "ImprintTypeCreated",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "maxSupply", type: "uint256", indexed: false },
      { name: "primaryPrice", type: "uint256", indexed: false },
      { name: "royaltyBps", type: "uint96", indexed: false },
      { name: "contentHash", type: "bytes32", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ImprintTypeCreatedWithSig",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "registrar", type: "address", indexed: true },
      { name: "maxSupply", type: "uint256", indexed: false },
      { name: "primaryPrice", type: "uint256", indexed: false },
      { name: "royaltyBps", type: "uint96", indexed: false },
      { name: "contentHash", type: "bytes32", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ImprintPurchased",
    inputs: [
      { name: "buyer", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "totalPaid", type: "uint256", indexed: false },
      { name: "platformFee", type: "uint256", indexed: false },
      { name: "creatorRevenue", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ImprintBoughtFromHolder",
    inputs: [
      { name: "buyer", type: "address", indexed: true },
      { name: "seller", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "unitPrice", type: "uint256", indexed: false },
      { name: "totalPaid", type: "uint256", indexed: false },
      { name: "royaltyReceiver", type: "address", indexed: false },
      { name: "royaltyAmount", type: "uint256", indexed: false },
      { name: "platformFee", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CollectionCreated",
    inputs: [
      { name: "collectionId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "mintPrice", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CollectionMint",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "collectionId", type: "uint256", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CollectionStatusUpdated",
    inputs: [
      { name: "collectionId", type: "uint256", indexed: true },
      { name: "active", type: "bool", indexed: false },
    ],
  },
] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
] as const;
